### ISSUE TITLE
Make e-mail text customizable(to improve spam rating)

### ISSUE THREAD

**Issue by 6uhrmittag** [CTFd/CTFd#1002]
I noticed that the built-in e-mail text are producing a spam warning. Two provider moved them straight to the spam folder.

https://www.mail-tester.com complained about:
- not enough text
- wrong encoding for special characters I'm using([admindōjō](https://admindojo.org/))[means I cant use `ctf_name`]

It would be nice to be able to be able to customize subject and text for all e-mails without the need out touching CTFd directly.
Additionally it would be nice to be able to use all defined variables in all three mail types.

**Proposal**

- make email text and subjects customizable via `config.py`
- add `ctf_name=get_config('ctf_name')` to all three
- add `name=name` to all three to greet the user with username
- use variable names instead of `{0}`,`{1}` in `def forgot_password(email, team_name)`

**Comment by ColdHeat** [comment]
I like this idea, thanks for suggesting it! 

It would be easy to implement this setting in `config.py` but I think it belongs in the application settings given that an admin may want to change it themselves. The real question is adding the ability to template those variables because it could cause issues if not done correctly. For example: https://www.palletsprojects.com/blog/jinja-281-released/

**Comment by pintman** [comment]
Further it would be nice to customize the URL of the reset-link. An instance running in a docker container behind a reverse-proxy will result in a 127.0.0.1 in these mails.

**Comment by ColdHeat** [comment]
Closed in #1238
