### ISSUE TITLE
Hint button deducting points after challenge is completed.

### ISSUE THREAD

**Issue by FedeCuci** [CTFd/CTFd#1005]
This is a little issue that I have spotted. When a user has completed a challenge and clicks on 'Hint' points are deducted even if the challenge is completed. I think it should say that the challenge is already completed and should not deduct points. 

I know it is small, but I already had one student that was curious about the hint and got points deducted from it.

Therefore, I think the hint button should still be clickable after completion so that the user can still see the hint.

**Comment by ColdHeat** [comment]
I think hints available after the CTF ends makes sense, but if the CTF is ongoing hints should still cost points. In the worst case, an admin can remove the award.

**Comment by FedeCuci** [comment]
I don't think I really understand what you mean. To me, if someone has completed a challenge, they should have the privilege to view the hint without losing points. 

However, I am sure you have a good reason. Could you maybe elaborate?

I am just trying to help is all, not trying to be rude.

**Comment by ColdHeat** [comment]
A person who has completed the challenge might give the hints away to a person who doesn't want to sacrifice points for a hint. I think if the competition is ongoing, it doesn't make sense to give anything away. Before unlocking a hint, the user does receive a confirmation so to me it seems okay. 

After the CTF it doesn't make sense to take away points since they couldn't get the solve anyway.
