### ISSUE TITLE
Feature Request: Optmize Challenge Entry

### ISSUE THREAD

**Issue by frohoff** [CTFd/CTFd#1008]
Previous versions of CTFd allowed for the entry of all the required fields for simple challenges (standard scoring, single static flag) on a single form with a minimal number of interactions/clicks which allowed for rapid challenge entry. 

Newer versions require far more separate steps: select "challenge type", "create" button, "flags" tab, "create flag" button, select "flag type", button "create flag", select "visible", "update".

Ideally this could be somewhat streamlined for these common, simple challenges so that they can be quickly entered. The best case would be all of these fields appearing on the initial form, defaulting to "standard" challenge type and "static" flag type (or allowing admins to configure a default value), and perhaps a checkbox widget for the "visible" field.

**Comment by ColdHeat** [comment]
I think it's difficult to keep this all in the initial form because ultimately the concept of flags and files are not really part of the challenge. A challenge can exist in CTFd without a flag. For example the Manual Verification Challenge Plugin on the [CTFd Store](https://ctfd.io/store/). 

I think the best approach here is after create we can show a modal that lets you add in fast defaults.

**Comment by ColdHeat** [comment]
Closed in #1151. Any new ideas should go into a new issue.
