### ISSUE TITLE
Feature Request: make a note about each users

### ISSUE THREAD

**Issue by nulLeeKH** [CTFd/CTFd#1052]
Sometimes we need to memo about abusing or support history for each users.

**Comment by jimender2** [comment]
I am currently working on this feature in https://github.com/jimender2/CTFd/tree/user-notes
I have 2/6 tests passing with the ones that are giving me trouble being the postgres and pymysql tests.

Other than that, all tests are passed and I can confirm that it works. I just need to add an icon to the page instead of reusing another on the page.

**Comment by nulLeeKH** [comment]
Thank you for your great work!!!

Everyone including me would be pleased with that.

**Comment by ColdHeat** [comment]
Currently working on this. This is how it looks right now:

![image](https://user-images.githubusercontent.com/166333/90095845-cfd78280-dcff-11ea-8bf8-15fc3b5d07b4.png)

**Comment by ColdHeat** [comment]
Closed with #1600
