### ISSUE TITLE
Certain fields not present in /api/v1/challenges

### ISSUE THREAD

**Issue by jedevc** [CTFd/CTFd#1164]
**Environment**:

  - CTFd Version/Commit: 97f5dca
  - Operating System: Linux
  - Web Browser and Version: N/A

**What happened?**

```
`GET /api/v1/challenges`
= `{'data': [{'category': 'demo', 'name': 'Hello World', 'template': '/plugins/challenges/assets/view.html', 'tags': [], 'script': '/plugins/challenges/assets/view.js', 'type': 'standard', 'id': 7, 'value': 10}], 'success': True}`
```

**What did you expect to happen?**

Same as when doing `GET /api/v1/challenges/7`, which gives 
```
`{'data': {'files': [], 'description': 'Hello there my friends', 'tags': [], 'id': 7, 'type_data': {'templates': {'create': '/plugins/challenges/assets/create.html', 'update': '/plugins/challenges/assets/update.html', 'view': '/plugins/challenges/assets/view.html'}, 'scripts': {'create': '/plugins/challenges/assets/create.js', 'update': '/plugins/challenges/assets/update.js', 'view': '/plugins/challenges/assets/view.js'}, 'id': 'standard', 'name': 'standard'}, 'hints': [], 'category': 'demo', 'name': 'Hello World', 'solves': 0, 'value': 10, 'state': 'visible', 'type': 'standard', 'max_attempts': 0}, 'success': True}`
```

In particular, the field of interest is `description` which is present in the list, but not in the individual get. Is there a particular reason that this field has been omitted?

**Comment by ColdHeat** [comment]
It's not there because it's doesn't really seem necessary and it were there would bloat the response. If you're drawing the description you probably want the other assets too so it wouldn't really make sense to only put description in the top level. If you really want all challenge resources available I think you would be better off making a new endpoint to give you that data. 

You could also perhaps PR changes to make the data returned mildly controllable by the client.

**Comment by jedevc** [comment]
Thanks, that makes sense. I might look later at trying to PR some changes to let the client specify.
