### ISSUE TITLE
Serve plugin assets with the correct mime type

### ISSUE THREAD

**Issue by Bibliofile** [CTFd/CTFd#1304]
**Environment**:

  - CTFd Version/Commit: 2.3.2
  - Operating System: Windows
  - Web Browser and Version: Chrome, latest

**What happened?**

When creating a plugin, I wanted to extract some helper functions out to a different file. Since I don't need to worry about older browsers, I was going to use a [JS module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) to encapsulate the work. I placed the module in my plugin assets directory and tried to import it. It errored:

> Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**What did you expect to happen?**

CTFd should serve assets in plugin asset directories with the correct mime type according to their file extension.

**How to reproduce your issue**

In `assets/update.html`

```html
<script type="module">
const root = `{{ get_config('APPLICATION_ROOT') or '' }}`
import(root + '/plugins/my_plugin/assets/helpers.js').then(console.log)
```

In `assets/helpers.js`

```js
export function hello() {
  alert("Hello world!")
}
```

**Any associated stack traces or error logs**

N/A

**Comment by ColdHeat** [comment]
Hi I wasn't able to reproduce this. It does look like JS files are being served with `application/javascript` as the Content Type.

![image](https://user-images.githubusercontent.com/166333/79312356-c4e52080-7ecc-11ea-878a-fe5796f53af1.png)

This also appeared to be the case with gunicorn instead of just the debug server. 

To test further I also added the following to `CTFd/plugins/challenges/assets/view.html` and also added your `helpers.js`

```
<script type="module">
import('/plugins/challenges/assets/helpers.js').then((module) => {
	module.hello();
});
</script>
```

It successfully executes:
![image](https://user-images.githubusercontent.com/166333/79312487-f65dec00-7ecc-11ea-80fa-c38c8bbb4633.png)

Do you perhaps have a better example to show for this?

**Comment by ColdHeat** [comment]
@Bibliofile can you provide more details for this?

**Comment by Bibliofile** [comment]
Sorry for the delay here! I should be able to check tomorrow & get back to you then.

**Comment by Bibliofile** [comment]
Well, this is really weird, it works now... No idea what I was doing wrong before, unfortunately I didn't save that code in a commit or stash. Thanks for looking into it!
