### ISSUE TITLE
Security Headers considerations

### ISSUE THREAD

**Issue by hugoprudente** [CTFd/CTFd#1431]
**Environment**:

  - CTFd Version/Commit: 2.4.2
  - Operating System: Linux
  - Web Browser and Version: All

**What happened?**
I would like to brainstorm the implementation for the core CTFd, of the following headers.

HTTP Strict Transport Security (HSTS)
Content Security Policy (CSP)
X-Content-Type-Options
X-Frame-Options
X-XSS-Protection

[https://flask.palletsprojects.com/en/1.1.x/security/](https://flask.palletsprojects.com/en/1.1.x/security/)

I had to implement such security feature for internal usage and I would like to know your thoughts on adding it to the Core of CTFd, I'm not using Flask-Talisman as is not necessary for basic configurations. 

The implementation configures the headers on the **config.py** and add the **nonce-<hash>** for the inline JavaScripts, Images and Styles.

**Comment by ColdHeat** [comment]
I don't think that these headers are really worth it. You could implement it as a plugin with Flask-Talisman but I think for the general installation, this is probably going to eventually cause trouble. 

Especially because CTFd doesn't have tight integration with a reverse proxy so some of the settings can't be automatically configured.

**Comment by hugoprudente** [comment]
Cool, I'll convert my implementation to a plugin using Flask-Talisman and let it available. 

Resolving this!
