### ISSUE TITLE
Enable Switching Teams

### ISSUE THREAD

**Issue by weems** [CTFd/CTFd#1588]
**Environment**:

- CTFd Version/Commit:
- Kali Linux:
- Chrome 84.0.4147:

**What happened?**
Mistake Made, one person needs to switch from one team to another
**What did you expect to happen?**
Ability to switch from one team to another
**How to reproduce your issue**
Make a team, have a team member accidentally make a team instead of joining your team
**Any associated stack traces or error logs**
N/A

**Comment by ColdHeat** [comment]
An admin is already able to remove a member from a team so that they can join a new team. The end user loses all of their progress in CTFd so I am very hesitant to implement team leaving behavior without a lot of consent when there's already a working solution (even if it is slow). 

If this was implemented, the end user would have to lose all of their data and progress upon team leaving. This would affect the team itself and the scoring data for the entire CTF. I'm not currently in favor of writing or maintaining any kind of behavior to merge data between users/teams. 

It also opens up the question of users creating fake teams to unlock hints or otherwise manipulate their scoring data.

Maybe this will be implemented if someone is willing to put in the work for it and demonstrate clear evidence that this wouldn't affect CTFs (public or private) negatively.

**Comment by ColdHeat** [comment]
I think I'm willing to consider team captains deleting teams if the team itself has no solves (maybe no submissions). If they do have data, then I would think they should still reach out to an admin.

**Comment by ColdHeat** [comment]
Captains of teams that haven't done anything can now disband their team. I am very hesitant to implement anything more than that.
