### ISSUE TITLE
sample walkthrough building challenge

### ISSUE THREAD

**Issue by deepgray** [CTFd/CTFd#179]
is there some documentation on a walkthrough of how you would build a challenge and load it in?

**Comment by ColdHeat** [comment]
CTFd does not really help in building challenges since it's meant to be the interface through which people access and solve your challenges. Sort of like how blog posts are hosted on Wordpress. 

There definitely should be a walkthrough of loading challenge into CTFd though. 

I'll look to add a setup flow page to the Wiki.

**Comment by ColdHeat** [comment]
You can now find a Getting Started page on the Wiki: 
https://github.com/CTFd/CTFd/wiki/Getting-Started#adding-your-first-challenge-to-ctfd
