### ISSUE TITLE
Hints as something integrated with the challenge[Feature request]

### ISSUE THREAD

**Issue by alme5** [CTFd/CTFd#197]
Possibility to include hints within the challenge. Some hints might be for free and others will be with points. We can enable hints from the very beginning of the exercise or at a certain point during the exercise.

**Comment by nategraf** [comment]
This is an interesting feature because of the variety of ways this can be implemented. For example, different CTF admins may want to implement the unlocking based on total time in the competition, number of of challenges completed, have them be bought for points, create a token based hint economy....

If you want a really simple solution for your own competition, the description allows for full HTML encoding and a free hint can be implemented with bootstrap and light JS to be revealed when you press a button. 

To create a system that works for many people there are two options in my mind:
1. Have any hint system be an admin side plugin
2. Have a basic hint system designed in such a way that the logic to reveal the hint can be easily swapped out, and have the default be the simplest possible mechanism (free hints)

**Comment by ColdHeat** [comment]
@nategraf brings up a point that I hadn't considered which was that hints are essentially the beginnings of an economy and different CTFs will want to do different things. 

An improvement to the plugin system makes the most sense. Currently on the testing branch I'm working on improving the plugin system to support custom types of Keys/Flags and custom types of Challenges. 

Next on the list is likely custom Hints. 

But the issue somewhat becomes how these hints will factor into score. The score calculation function is the most complex DB query so making changes to it takes a good amount of time. Likely the eventual solution would be to tie the Awards and Hints systems together so that when you unlock a Hint you also receive an award subtracting points away from you.

**Comment by alme5** [comment]
Hello
Here is what I had in mind:
Question 1 - Correct answer gives you 10 points. There are three hints available. If you take the first hint you lose 1 point. If you take the second hint you lose 2 and if you take the third you lose 3. so if you take all those hints you end up loosing 6 overall points. Those are deducted automatically as soon as you take the hint from the overall points you have gathered up to that point. If no points allocated and you get the hint, you go to minus points.
