### ISSUE TITLE
Accessing extra challenge fields from the API

### ISSUE THREAD

**Issue by Cryptanalyse** [CTFd/CTFd#2118]
Could the API endpoint `/api/v1/challenges` be modified (ideally by a plugin) so that it returns custom fields added by a challenge plugin? For instance, dynamic challenges feature some extra fields like maximum, minimum, decay, etc. and I would like to access those in a custom theme. Currently, the dynamic challenge plugin allows to reach those fields in the challenge modal (thanks to the `read(cls, challenge)` function), but as far as I known, it is not possible to retrieve those for _all_ challenges at once in the data returned by `/api/v1/challenges` unless `CTFd/api/v1/challenges.py` is modifed.
Is there an obvious way I'm missing? This would be a nice feature otherwise.

**Comment by ColdHeat** [comment]
You can always modify any API endpoint using the plugin system. You can make it respond with whatever data you'd like if you need to. 

I get why you would want to do this but I personally think that having `/api/v1/challenges` only list data that's in the main Challenges model is the right decision. Doing otherwise would add weird dynamic structural changes to the API response. And in some situations the challenge type plugins that are loaded changes which I think could break the endpoint maybe. 

We could add an `extra` section or something like that that would have data that is configurable by the plugin but I don't think the work is worth it. 

I think the plugin system is the right way for you to approach this. If other people really end up needing this, we can take a look again.
