### ISSUE TITLE
CTFd Config Question.

### ISSUE THREAD

**Issue by dhje0ng** [CTFd/CTFd#2191]
hello sir. I want to read the settings of the CTFd platform.
For example, if the score public mode is public or private, it can be obtained through below.
`{{ Configs.score_visibility }}`

However, I want to get the values ​​of Name Changes, Team Created, etc. of Account when operating in team mode, but it seems that the decoration is not specified.

Can you solve this problem?

thank you.

**Comment by ColdHeat** [comment]
You should be able to use `get_config()` from the theme. You will need to look up the specific key that you are looking for from the database. I'm pretty sure you are able to use `Configs.name_changes` because `__getattr__` is defined for the `Configs` global but you can still use `get_config()` in any case.

https://github.com/CTFd/CTFd/blob/02c08f50cc1be2a058a9f0b1eb27dd6a30652945/CTFd/utils/initialization/__init__.py#L88
https://github.com/CTFd/CTFd/blob/02c08f50cc1be2a058a9f0b1eb27dd6a30652945/CTFd/constants/config.py#L51

**Comment by dhje0ng** [comment]
thank you sir.
