### ISSUE TITLE
Custom Theme in React

### ISSUE THREAD

**Issue by reteps** [CTFd/CTFd#2321]
Would like to develop my custom site theme in React, and then bundle up the CSS/js files and add them to the site.

Are there any limitations I could run into? Is this a feasible goal?

**Comment by ColdHeat** [comment]
It's feasible but likely more difficult than it's worth. I would take a look at what https://github.com/CTFd/core-beta does and then see what comopnents could be converted into React. 

CTFd is designed around Flask so it makes a lot of use of Jinja templates so most of the time it's easier to just add interactivity on top of a template instead of doing a SPA with React. I did experiment with it a bit but core-beta turned out to be the best version of all the experiments.
