### ISSUE TITLE
Making CTFd accessible from the outside

### ISSUE THREAD

**Issue by mpentler** [CTFd/CTFd#256]
Apologies for the rather noobish question, and it may not even be possible, but I'm having difficulty accessing my CTFd from outside my local network.

I've tried adding '.*' as a regex to config.py in the TRUSTED_PROXIES section but it doesn't seem to allow any connections, and I'm pretty sure that regex would match anything. This happens both when running CTFd on my laptop and also running on an Amazon EC2 instance with an inbound rule set to allow port 4000 from 0.0.0.0/0 (all addresses).

What am I missing? Is it something to do with the Docker container? Do I have to expose another port somewhere? I'm using the debug serve.py method for running it. Should this work or is this just my stupidity?

**Comment by mpentler** [comment]
My bad, was the serve.py host parameter. Idiot!

**Comment by ColdHeat** [comment]
Hey @mpentler I changed serve.py to go from 0.0.0.0 to 127.0.0.1 because it's very ill-advised to use serve.py to host CTFd for the internet. By default it uses debug mode and the Flask built in server isn't that performant. I think you should look into hosting CTFd with gunicorn :) 

Glad you figured it out though!

**Comment by mpentler** [comment]
Oh don't worry it's for like 7 people and all very low key. And it uses bugger all resources on an Amazon Free Tier EC2 instance. Anyone wanting to make their own CTFs for a small group of friends should look at this method for deployment. Happy to write a guide for the wiki if you want.
