### ISSUE TITLE
The Decay function is applied to all users at the same time.

### ISSUE THREAD

**Issue by misohouse** [CTFd/CTFd#2577]
CTFd version : 3.6.1

Here's the situation I want

1. the first person to solve a particular question gets 150 points
2. the second person to solve the question gets 148 points
3. the third person to solve the question gets a score of 146
.
.
.

So I set up the Challenge settings as follows
```
Current Value : 150
Initial Value : 150
Decay Function : Linear
Decay : 2
Minimum Value : 100
```

**(Problem) This way, the first, second, and third person to solve the problem will all receive 146 points.**

As more users solve the question, the scores of those who have already solved the question will change accordingly.

Changing the Decay Function to "Logarithmic" only increases the width of the decay, but it still results in the same score for all users.

How can I fix this problem?

**Comment by pandatix** [comment]
That is the normal behavior of CTFd. With the strategy you document, players will adopt a "greedy" mindset: the first to solve wins, leading to an increase of shareflag and toxic communications.

If we imagine a not-so-well balanced CTF (it happens a lot), there will be a low-level team "Beep" and a high-level team "Flop" but late to the event. Beep will be a top leader in the scoreboard because they were fast at the beginning on intro challenges despite Flop will be at the bottom because they were late. This does not seem fair to me, especially in an objective to educate or have a good time with other good players: we can expect Flop to be in the top of the scoreboard, not Beep.
Furthermore, if the CTF runs through the night, it would imply that the top best players such as Flop only require to go fast then sleep and leaves with the prizes, but others such as Beep must work all night to reach the 1st quarter, so being tired and no prize. With the current strategy, it requires Flop to always work to build a gap between them and Beep and be sure of their top place in the scoreboard. It is more challenging without pushing toward shareflag and toxicity.

To technically implement this, I defend the idea of a plugin that reimplement the DynamicChallenge with such a behavior rather than making it the default behavior.

**Comment by misohouse** [comment]
@pandatix

Ah.. I thought I was doing something wrong but it's normal, thank you for your response.

I looked up the plugin as you said and found the link below.
https://docs.ctfd.io/tutorials/integrations/webhooks/using-api-first-blood/

But the link below seems to only give extra points to 'Firstblood', is there any plugin that can give more points to whoever solves the problem first, like I want?

**Comment by pandatix** [comment]
If you are only looking for a strategy like "whoever solves the problem first [gets] more points", the firstblood approach is the one to stick with. Elseway, if we are still discussing of the original strategy you described, I am note aware of a plugin that implements it...

**Comment by misohouse** [comment]
@pandatix

I want the number of people who solve the problem to decrease as more people solve it.

For example, if the first person solves it and gets 150 points, the next person solves it and gets 148 points, the next person solves it and gets 146 points, and so on.

I would appreciate it if you could tell me to a plugin that can do what I want (that you mentioned you know of).

**Comment by pandatix** [comment]
Sorry but...
>  I am note aware of a plugin that implements it

I don't know a plugin that does so.
