### ISSUE TITLE
Implement 'Dynamic Scoring' Option

### ISSUE THREAD

**Issue by grant-h** [CTFd/CTFd#330]
Recent CTFs (LegitBS 2016, Polictf, Google CTF, etc.) have opted to weight challenges based on the number of teams that solve it. For example, [Polictf](http://www.polictf.it/instructions.html) starts all challenges regardless of difficulty at 500 and decreases the points on every solve.

**Comment by ColdHeat** [comment]
Hmm... CTFd is very tied to it's current scoring model but I believe this can be done through a plugin. I'm just not sure if the team score/place calculations can be overridden by a plugin. 

I'm not sure this should go into CTFd master because it could be the start of additional CTFd complexity. I think making the scoring system something that can be controlled by a plugin makes the most sense.

**Comment by gigajum** [comment]
I've modified the CTFd source to support dynamic points while also having static points. I added 3 values to the config: minimal score (the score will not go below this value), maximal score (initial value for 0 or 1 solve) and a decay value which controlls indirect how much points each solve "removes". The database only needs a new challenge column to store if it's dynamic or static.

I started developing this 3 months ago for a local ctf which ran last weekend. Since i have not seen a quick way to implement this functionality through a plugin, it's in the main code. Should i create a pull request or should i try to move it into a plugin?

modification to config:
![ctfd1](https://user-images.githubusercontent.com/4034327/30135702-3d758e18-935c-11e7-978c-6e1522c8f4ee.png)
modification to admin challenge modal dialog:
![ctfd2](https://user-images.githubusercontent.com/4034327/30135703-3d774c8a-935c-11e7-88d1-41e170269f63.png)

**Comment by ColdHeat** [comment]
Oh boy! I wasn't even sure if this could be done with the current overall database design but if you make your code open source (I don't see it on your Github profile) I can give you a better idea of what direction I think it fits best as. 

If you make a PR I'm happy to work with you to get it into a state that you can merge it in or help you pluginize it or add it as a challenge type.

**Comment by gigajum** [comment]
It was forked into a private repo since we did not know if we will use it or if everything runs as expected. 

I created a fork in my profile and applied the changes.

**Comment by ColdHeat** [comment]
I think your implementation works well but integrating into master could be tricky. 

As a plugin, there isn't enough customizability within CTFd yet to allow a plugin to dictate how a challenge should be marked solved unless you were to hijack an entire endpoint. Right now, as far as CTFd is concerned, solving a challenge means inserting a Solve and that's it. 

I could see this implemented as a plugin if `challenges.py` were to pass marking challenges as solved into the [challenges plugins](https://github.com/CTFd/CTFd/blob/master/CTFd/plugins/challenges/__init__.py). The challenge plugins would have some more classmethods. Perhaps `attempt`, `solve`, and `fail`.

I don't think it makes sense to merge it into master because it means explicitly having certain behavior for certain challenge types baked into the master logic.

I think it would be great if other CTFd users and devs could weigh in here on their opinions.

**Comment by hackmethod** [comment]
@gigajum This is brilliant!  I started working on this last week and was digging into how it would change in the database or how indepth I would need to go to make it work.  My idea was Max points, Min points, and a degrading percentage after each solve like .02%  I think this would benefit the community greatly as most CTFs are moving towards this scheme.  It prevents flag hoarding, makes the hint deduction system obsolete, and thwarts cheating with users creating false accounts to use the hints without spending them on their primary account.  Nice work!

**Comment by Hypersonic** [comment]
I've got a few thoughts on this:
1. I'm really into the idea of CTFd having dynamic-scoring, but I think it should be implemented in a plugin, as has been mentioned (though the patch is a great demo for how we could start to get this done),
2. A decision needs to be made with regards to the scoreboard, particularly the graph, which I didn't see in the demonstrated patch: What score should the scoreboard be tallying for each team:
    * Do we want to show the scores-at-the-time, as in what the rankings looked like at that moment in time, with their values at that time, or,
    * Do we want to show the scores-as-they-would-be, as in what the rankings would look like with challenges at their current values
3. Do we want to support fancier score decay functions? Is that even worth the effort?

I probably will have other thoughts about this at some point, but those are my main questions for any implementation of this right now.

**Comment by wroersma** [comment]
How about challenge that remain open with both right and wrong answers. Example 1: which IP addresses would you like to block? For every C2 blocked get +100 points for every critical business IP lose -100 points.

**Comment by wroersma** [comment]
Sorry I just noticed this is also mentioned in https://github.com/CTFd/CTFd/issues/353 I'm happy to write it if someone can point me the direction that would be best for the project.

**Comment by ColdHeat** [comment]
You can take a look at the new staticmethods for Challenge Types @wroersma: https://github.com/CTFd/CTFd/blob/a20e7eae63e717335f427706854b2988f75d3e75/CTFd/plugins/challenges/__init__.py

This allows challenges to define the logic for when challenges are attempted, solved, and failed.

**Comment by wroersma** [comment]
Thanks!!! I'm so pumped to find a CTF scorebot with active devs. I'll see what I can do and submit a pull request for review soon.

**Comment by ColdHeat** [comment]
Because of some recent changes to CTFd's challenge type plugins, it should now be pretty trivial to add this as a plugin. 

The [built in challenge type](https://github.com/CTFd/CTFd/tree/master/CTFd/plugins/challenges) can be copied and modified to perform basic dynamic scoring (e.g. -1 point per solve). 

In order to implement variable decay rates, we need to have custom tables per challenge type which isn't something that CTFd yet understands.

**Comment by ColdHeat** [comment]
I'm removing this issue from the 1.0.5 milestone because I wouldn't want it to hold up a release because this is going to become a plugin. 

I created a new issue for the requirements for this plugin here: https://github.com/CTFd/CTFd/issues/426

The changes here https://github.com/CTFd/CTFd/pull/425 implement what is needed to implement this concept fully. 

I'm not sure if I will take on the task of creating and maintaining this plugin but it does seem like this is the "future of CTF". Perhaps it is worthwhile that CTFd releases an official way to do this.

**Comment by ColdHeat** [comment]
CTFd now has a plugin which adds the dynamic challenge type which implements dynamic scoring behavior. It is available here: https://github.com/CTFd/DynamicValueChallenge

Further discussion on this topic should take place there.
