### ISSUE TITLE
Hint modals should allow for a Markdown preview

### ISSUE THREAD

**Issue by ejohn20** [CTFd/CTFd#444]
<img width="562" alt="screen shot 2017-11-08 at 6 22 15 pm" src="https://user-images.githubusercontent.com/14187430/32581949-e314ddd4-c4b1-11e7-80f1-b2e217243474.png">

When adding a new hint, this text causes an alert box to fire:
<svg/onload=alert('XSS')>

**Comment by ColdHeat** [comment]
Admins are considered trusted users so I don't really consider this a vulnerability. How does a random non admin CTFd user use this to take control of another user's browser? 

An issue in terms of usability I would agree. I presume you were trying to add in an XSS payload which was rendered as HTML inside of page form. 

Usually this is intentional so that you as an admin are able to write HTML inside the hints. If you want to write actual HTML I would probably encode the angle brackets first.

**Comment by ejohn20** [comment]
Correct. I was just surprised this wasn't encoding it's data. I encoded the entity myself to correct it, but wanted to let you know in case you were not aware. You can close the issue if you don't feel it's worth it.

**Comment by ejohn20** [comment]
Would supporting markdown in the hints be a better way of handling this?

**Comment by ColdHeat** [comment]
Hints actually do support Markdown when they are rendered to the user. They just aren't being rendered as markdown in the admin panel. 

And it wouldn't really help because Markdown should allow for the insertion of standard HTML tags. I think the correct approach here is to to use the same Write/Preview technique used by the challenge description interface. I'm going to change the issue title again to more properly reflect that goal.

**Comment by ColdHeat** [comment]
Closed in the 1.1 branch.
