### ISSUE TITLE
Running server.py and docker-compose up return different enviroments

### ISSUE THREAD

**Issue by jarvisjarb** [CTFd/CTFd#516]
**Environment**:

  - CTFd Version/Commit: Master
  - Operating System: Ubuntu server 16.04
  - Web Browser and Version: Chrome

**What happened?**
I probably have missed something important but I would kindly appreciate you help. 
After playing with running ` "python server.py"`, I have installed docker-compose, and ran `"docker-compose up"`.
 All of the configuration of CTFD I have previously made (challenges for example) are not showing. Starting the `"server.py"` makes them appear again. 

How can I make this work ? 
(I have already tried using the export and import features, but with no success. What am I missing ?)

**What did you expect to happen?**
See the same challanges and setting when running both docker-compose and server.py

**How to reproduce your issue**
I ran `server.py`, made some edits and configurationsm stopped it, and ran `docker-compose up`

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
There is no script called `server.py` in CTFd but there is one called `serve.py`. 

`serve.py` and `docker-compose up` use two different database backends by default. The first uses sqlite and the second uses MySQL. This is for the most part intentional. 

If you want to run using your SQLite database you should delete the DATABASE_URL line in docker-compose.yml.

**Comment by jarvisjarb** [comment]
Thanks! Got it!
