### ISSUE TITLE
Feature Request: HTTPS by default

### ISSUE THREAD

**Issue by benichmt1** [CTFd/CTFd#533]
Since this is a security-related project, best practice would indicate the need for HTTPS, especially for the login form. In my deployment I was able to manually deploy it by using the --cert options in gunicorn, but it might be helpful to generate a self-signed certificate as part of the install process, or prompt the user for the path of their valid certificate.

Let me know if you think this would be a helpful PR and I can also add instructions to the documentation.

Thanks

**Comment by ColdHeat** [comment]
It isn't the responsibility of CTFd to manage the entire stack nor should it be. Ultimately CTFd is a web application and dealing with server configuration is really not something it should deal with because situations can differ drastically. 

Managing SSL certificates for the user is asking for a lot of trouble.
