### ISSUE TITLE
BUG: Unable to Edit Challenges as Admin When Using Subdirectories

### ISSUE THREAD

**Issue by mrchisel14** [CTFd/CTFd#545]
**Environment**:
  - CTFd Version/Commit: 1.1.1/2e2d458f36278d14c26ec455a11ca5775bf8221f
  - Operating System: Ubuntu 16.04
  - Web Browser and Version: Chrome Version 63.0.3239.108

**What happened?**
When using subdirectories you are unable to edit a challenge as an administrator (405 error).

**What did you expect to happen?**
You should be able to update the challenge without a 405 error.

**How to reproduce your issue**
Set up CTFd on a subdirectory like /ctfd/ and attempt to update a challenge through the admin panel

**How to fix**
Edit [standard-challenge-update.njk](../tree/master/CTFd/plugins/challenges/assets/standard-challenge-update.njk) line 17. Replace request.script_root with script_root

**Comment by ColdHeat** [comment]
Thanks for reporting this. Will be fixing this in master in a bit.

**Comment by AdityaVallabh** [comment]
This issue still occurs in the latest commit `bf799fb22040a32bd2c8dcebecb010042782bc83`

I cloned a fresh copy of the CTFd Structure, "MonkeyPatched" a few files as given [here](https://github.com/gevent/gevent/issues/1235), ran using `python3 serve.py`, logged in as admin, created and tried to update a challenge.

But instead of updating as expected, I get the error: `HTTP/ 405 Method Not Allowed`.

@ColdHeat @mrchisel14 the fix stated above is no longer valid as the structure has changed since then. Any other fixes that I can try?

**Environment:**
- CTFd Version/Commit: 2.0.4/bf799fb22040a32bd2c8dcebecb010042782bc83
- Operating System: Ubuntu 18.04
- Web Browser and Version: Mozilla Firefox (Quantum) 65.0.1 as well as Chrome Version 72.0.3626.121
