### ISSUE TITLE
Fatal Error: init() issue

### ISSUE THREAD

**Issue by mike-bailey** [CTFd/CTFd#554]
**Environment**:

  - CTFd Version/Commit: Tried multiple including latest
  - Operating System: Amazon Linux
  - Web Browser and Version: N/A Browser

**What happened?**

```
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 364, in import_app
    app = eval(obj, vars(mod))
  File "<string>", line 1, in <module>
  File "/opt/LessShit/CTFd/CTFd/__init__.py", line 90, in create_app
    theme_loader = ThemeLoader(os.path.join(app.root_path, 'themes'), followlinks=True)
  File "/opt/LessShit/CTFd/CTFd/__init__.py", line 46, in __init__
    super(ThemeLoader, self).__init__(searchpath, encoding, followlinks)
TypeError: __init__() takes at most 3 arguments (4 given)
```

When I try to start via multiple methods after an update and reboot.

**What did you expect to happen?**

A clean restart.

**How to reproduce your issue**

Provide more details as to what you'd want, please? I don't want to zip sensitive stuff.

**Any associated stack traces or error logs**
 See above

**Comment by ColdHeat** [comment]
Hmm.... what version of jinja2 is installed? Why Amazon Linux over simply Ubuntu? Are you doing something special? 

The code that should be being called here is Flask/Jinja related.

**Comment by mike-bailey** [comment]
Sorry, my pip setup was so brutally f'd it actually had requirements already satisfied with jinja2 but jinja2 wasn't actually installed. Thanks for the prompt response! lol

**Comment by mike-bailey** [comment]
Actually while I have you, I did a pip uninstall and a pip reinstall and now all our data is gone, I thought it was using SQLite, did something change that would've caused this to break? Thanks. @ColdHeat

**Comment by ColdHeat** [comment]
Not really. CTFd automatically takes migrations now so it is vaguely possible that a migration overwrote the database but sqlite is special and doesn't really like migrations so it doesn't really use them. 

Are you sure you are pointing to the right database? Perhaps you accidentally created a new one?

**Comment by mike-bailey** [comment]
I ran `create_app` would that have overwritten it?

**Comment by ColdHeat** [comment]
It won't overwrite an existing database file.

**Comment by ColdHeat** [comment]
Overall CTFd is very hesitant about making database changes and only recently did I change this to make migrations automatic but it's really more likely that something will crash because of failure than your database will be deleted. 

You should check to make sure that you weren't actually using a different database file or MySQL/Postgres. Perhaps config.py changed and you accidentally reverted some changes you made.

**Comment by mike-bailey** [comment]
This was our config.py (still is)
https://pastebin.com/tt9mN5wE

As far as I know, it wasn't overwritten. Am I wrong in thinking I should have a ctfd.db or something? All I did was pip uninstalls and reinstalls, move the directory (cleanly), admittedly exposed permissions a bit, and that's about it.

**Comment by mike-bailey** [comment]
It exists, but appears to have been overwritten.

**Comment by ColdHeat** [comment]
If it was indeed overwritten then that's probably a bug. But I would need to know the exact scenarios it happened under because if the file is there SQLAlchemy shouldn't overwrite it.

**Comment by mike-bailey** [comment]
Only detail I haven't mentioned was I ran another copy (in a different directory) of CTFd first and it dumped to setup, then I killed it and ran our original copy.

**Comment by ColdHeat** [comment]
I just copied over a database file from a v1.0.5 install into a v1.1.1 install and forced automatic migrations to run. 

I got a migration failure trying to create tables because the tables already exist. I also looked at the databases and the only change was that the updated install has an empty alembic_version table created.

**Comment by mike-bailey** [comment]
I never updated or ran migrations.

**Comment by ColdHeat** [comment]
Migrations automatically run in versions >= 1.1.0. What were you trying to do then?

**Comment by mike-bailey** [comment]
Well, first thing's first I updated my actual system. Then I was first trying to migrate the service to a non-root user by changing ownership of the directory and moving it, then realized that user was in pip hell, so I kept to root and ran it as I usually do (gunicorn)

**Comment by ColdHeat** [comment]
It's tough for me to say what's going on without actually looking at the box. CTFd used to be very adamant about not running migrations without confirmations but this causes deployment issues for people. 

But same thing goes that migrations usually just fail on sqlite and if the version hasn't changed and the file still exists, SQLAlchemy doesn't just delete the existing database. It wouldn't make any sense because then the database would get destroyed on every run. 

I might try to run a find command to see if perhaps the database file exists somewhere else on the filesystem or check the environment variables to see if CTFd is configured to use something else that's overriding config.py.

**Comment by mike-bailey** [comment]
In a shocking twist, I was messing wit the wrong environment entirely. Docker had an exception and turned off the container and wouldn't turn it actually on. I'm bad. I'm so sorry for the inconvenience..   Consequence of doing maintenance on a server I didn't set up.

**Comment by ColdHeat** [comment]
That's okay. It happens 😄
