### ISSUE TITLE
Exports/Imports rewrite

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#567]
Exports/Imports is probably the buggiest feature of CTFd. Exports are fragile, they don't take into account extra tables a plugin might have generated and they have high chances of failure because they try to allow organizers to combine existing data with previous data. They are also pretty version dependent. 

A majority of this feature needs to be rewritten. The format itself I do not believe needs to change I think the approach and amount of features it has needs to change. 

From a preliminary review:

* Add a new segment called extra which looks at tables which were not generated by CTFd
* Do not attempt to normalize ID numbers at all. Simply pass through the backup into the database. 
* Give less control over during import. The content of a backup should automatically be detected. 
    * This might imply that we generate ALL json files but do not populate them. 
* We probably shouldn't allow the combination of two backups into one CTFd instance aka backups should be idempotent. 
* How do we make sure that backups also run through migrations to update to the current version?

This likely will have to be a backwards incompatible change. We need a single cohesive structure for the future of CTFd.

**Comment by AaronLayereDefense** [comment]
This post notes a bug I've experienced after importing solve data.

> I've setup an instance of the "ctfd/ctfd:latest" docker image, and am experiencing a bug with the "Challenges" tab after importing a backup. The backup included data of solves, teams, config, and challenges. Newly created accounts get a status code of "500 internal server error" when requesting the "/solves" endpoint, but teams that were imported in the backup get a status code of "200 ok". The "Challenges" tab requires getting data from the "/solves" endpoint, and the result is that newly created teams can't view "Challenges", while imported teams can. I've discovered that if I only import teams and challenges, and not solves, this error does not occur. This leads me to believe that the ctfd backend has a bug somewhere in the solves/challenges import and/or display code.

I also want to note that I think the import button in the admin config page needs visual feedback when clicked. When importing data for the first time, I accidentally imported the same backup multiple times. I could not tell if the first time I clicked the import button was successful. I think visual feedback indicating success or error would prevent this.

**Comment by mjaaland** [comment]
It seems that HINTS are not being exported at all, using the Web GUI. That would be great to get fixed.

**Comment by mjaaland** [comment]
I am getting "integrity errors" when I try to import my challenges. I will link to one export here: https://www.dropbox.com/s/1a9ng7s1mxwalaz/SDL204_207.2018-09-13challenges.zip?dl=0 

Importing this gives me these errors. Maybe because I have special characters in it, I don't know.

**Comment by reyammer** [comment]
Let me add some thoughts:

- I'm getting errors when importing instances with "dynamic challenges". It seems that the dynamic_challenge table (used by the dynamic challenges) plugin is not taken into account in the export. Note: the import itself actually appears to be successful, you get errors when you go to admin/challenges with some "dynamic challenge was deleted" error (due to missing entries in "dynamic challenge"). (Happy to open a new issue, just let me know.)

- FWIW, I agree with "We probably shouldn't allow the combination of two backups into one CTFd instance aka backups should be idempotent." I assumed that "import" was like "take the DB I've exported and create an exact copy", while it seems to be "add to the current DB whatever was in the previously exported DB". I guess this could also be useful, but a copy/paste-like export/import of the full DB feature would also be nice (as a workaround I'm just copying the actual ctfd.db file...)

**Comment by ColdHeat** [comment]
@reyammer thanks for the input. Your first point is known and slated for implementation soon. 

No need to make a new issue. There were some initial ideas behind being able to combine exports as you can see but it's made problems unnecessarily complex so they're going to be scrapped.

**Comment by ColdHeat** [comment]
An improved version of imports/exports should be available now in the 2.0.0 branch. If anyone tests it out it would be great!

**Comment by ColdHeat** [comment]
This code appears to work in 2.0.0 so I am removing this from the milestone and will close it out after it makes it to master.
