### ISSUE TITLE
XSS in team name field

### ISSUE THREAD

**Issue by yunolikeme** [CTFd/CTFd#592]
I noticed that there are a few reports of XSS and you don't seem to believe that XSS from a privileged user is a problem.  I have found an XSS where a user can target an admin user.  

If someone makes a team name with a script, when an admin user tries to delete the team, the script will execute in the popup window.  Case in point, iframe in the demo environment.  

![ctfdxss](https://user-images.githubusercontent.com/25513534/37736294-8bb3d18c-2d1e-11e8-8656-12013911897c.jpg)

**Comment by ColdHeat** [comment]
Okay this is a reasonable issue. 

XSS from a privileged user to a privileged user is not a problem because there is no escalation.

**Comment by 20esaua** [comment]
@ColdHeat I know this issue is old, but this comment is not responding to this issue. I disagree with your assertion regarding XSS without escalation. Although self XSS is of significantly lower severity than remotely-exploitable reflected/stored XSS vulns, it is an easy fix and should be fixed. Otherwise, it is possible for the vuln could be chained with another vuln and used in a practical attack. XSS is an easy fix 99% of the time, so it's almost always worth the effort to go ahead and fix it even though a practical attack may not seem apparent.
