### ISSUE TITLE
XXS in Notification 

### ISSUE THREAD

**Issue by bl00dh0und** [CTFd/CTFd#905]
**Environment**:

  - CTFd Version/Commit: Version 2.0.4
  - Operating System: Ubuntu 18.04 
  - Web Browser and Version: Firefox 65.0.1

**What happened?**
While playing around with CTF'd i noticed you can inject javascript into the notification and every action the user does will trigger this. While you can only inject notification as an administrator, i still feel this is a security issue. 

If a administrator uses a weak password, a malicious user could create a keylogger and fetch users password. 

**What did you expect to happen?**
I suspsect the script tags to be filtered 

**How to reproduce your issue**
<script>alert(1)</script> in the title bar from the notification

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment]
In the future please send any potential security vulnerabilities to support@ctfd.io. 

Secondly, CTFd doesn't consider admin to admin XSS a vulnerability. You are not achieving any form of privilege escalation. Admin to user XSS is also not a vulnerability. 

To consider XSS a vulnerability you need to demonstrate user to admin privilege escalation. How does every action a user do trigger your javascript?

**Comment by hashtaginfosec** [comment]
Kinda shocked this was closed with a comment that it's not a vulnerability. Have you not considered a rogue admin scenario? How about a rogue admin stealing another user's cookies to hijack their session and mess with their flags/profile/etc? How about a rogue admin submitting flags on another user's behalf?

**Comment by ColdHeat** [comment]
Admins have absolute ability in CTFd. They can **ALREADY** modify any flags, profile, settings, etc. Admins can also generate correct submissions for users. 

CTFd allows admins to generate HTML content which includes script content because of the flexibility it allows. If there were other user roles this might be a different story but there are only two user roles in CTFd.

**Comment by ColdHeat** [comment]
@20esaua If you want to continue this discussion you can comment in this issue. 

XSS can often be an easy fix and hence it was fixed in the other issue because it presented a legitimate issue with real concerns. 

However you seem to lack some understanding of XSS and how much power CTFd gives the admin user. 

First, any admin to user XSS is possible via most of the content creation areas because admins are allowed to create HTML/CSS/JS content. This is an intentional design decision and likely will not be changed until a 3.0 release or any release that adds multiple types of users. If you really want to remove this behavior now, you are free to create your own theme or PR the necessary changes to move to VueJS,  React, or some other front end library (taking into account what's already in the milestones). 

Secondly, XSS gives one user the ability to impersonate another user and conduct actions as them. Assuming an admin attacks another admin using XSS, they haven't achieved any new functionality. An admin could already have reset the CTF, changed content, etc. They could have achieved everything they could have before. In addition, right now CTFd only records IP addresses and doesn't have an edit history so you couldn't even fraudulently have an admin edit something and then blame it on them. 

Even if you were to conduct a login/logout XSS to force an admin to switch accounts, what would that achieve? 

If you can demonstrate an issue with real security impact *then* we can discuss accelerating some changes from the later milestones but thus far most of these issues seem to harp on the concept of XSS versus understanding what exactly CTFd is providing to the admin user.

**Comment by 1Jesper1** [comment]
For someone who would like to fix the admin => admin/ admin => user XSS vulnerabilities, I found some more:

1. /admin/notifications
XSS in title and content when creating a notification.

2. /notifications
Clicking on notifications triggers the XSS in notifications.

3. /admin/pages/3#
You are able to insert XSS in the page content.

4. /admin/challenges/1#preview
You are able to insert XSS in the challenge content.

5. /admin/challenges/1#preview
You can insert a link with javascript:// protocol.

6. /admin/challenges/1#preview
You can create a hint with XSS in the content.

7. /admin/statistics
Hover on item triggers XSS in solve-percentages-graph. 

8. /challenges
XSS triggers when challenge has XSS in title.

**Comment by 1Jesper1** [comment]
@ColdHeat Maybe the [https://demo.ctfd.io/](https://demo.ctfd.io/) could be a risk for admin => admin/ admin => user XSS?

**Comment by ColdHeat** [comment]
We are planning on making XSS less of an issue in a future version of CTFd. If you'd like you can try enabling the `HTML_SANITIZATION` config in config.ini/config.py. This is a beta feature but it should attempt to sanitize XSS out of any input, admin or otherwise.

If you find an issue with `HTML_SANITIZATION` enabled it's definitely a much more interesting issue!

@1Jesper1 , the demo is a pretty locked down server. Everyone is admin there essentially so I don't much of an issue there. Perhaps if you can demonstrate that a publicly shared admin account there has some kind of security impact to other CTFd instances perhaps or to other users. But that said we might just enable`HTML_SANITIZATION` on the demo instance to try it out.
