### ISSUE TITLE
Discord as a replacement for Slack?

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/CTFd#964]
The CTFd Slack was setup a long time ago to get communication out of Github issues and make it easier to share information. Since then it's grown to contain a number of private channels and act less as a place for open source support. Also there have been incidents in the past with Slack misconfigurations and abuse.  

Slack simply is designed more for trusted team member communications than communication between members of a freely accessible community. 

I have been looking at replacements for Slack and felt that Discord was a superior community chat system given that there are more moderation capabilities. Slack has a superior set of integrations but those integrations (as they're used now), are not a huge benefit for open source users. 

I'm opening this issue to gather feedback and see if anyone feels strongly about Slack or Discord.

**Comment by nategraf** [comment]
I'd support moving to Discord. I use it for other open-source communities (e.g. https://discord.gg/rust-lang) already and I think it works quite well.

**Comment by arkag** [comment]
I'm not against it. My work uses Slack for Engineering but the majority of comms is on another application. I use Discord a lot for other communities, so one less reason to use Slack is welcome!

**Comment by Helithumper** [comment]
Hack@UCF has been thinking the same for over a year now. We end up sitting on slack anyways. I have been part of multiple communities which use Discord as their point of contact with the community and I have yet to experience any significant issues. In fact, many CTFs are transitioning their communication channels to Discord off of IRC as well

**Comment by arkag** [comment]
I think the positive reception Discord receives over Slack is mostly due to the use of it's application over Slack. I log in once and get access to all of my communities, and it just operates better. I have less than half the communities on Slack that I do on Discord and the Discord app works *much* *MUCH* better than Slack. Loading times are low, and it has a native dark mode which people have been bugging Slack for for years.

/rant

**Comment by Helithumper** [comment]
I will also say that, suprisingly, Discord is MUCH faster at loading images / uploading images

**Comment by wroersma** [comment]
Discord > Slack . Do it

**Comment by lodi-g** [comment]
Discord is Slack but with more features and less loading times (and a dark theme!). I'm in.

**Comment by benichmt1** [comment]
How about Keybase?

**Comment by arkag** [comment]
I would be very into something like Keybase. I'd love a reason to use it more. I'm worried about general adoption, though.

**Comment by eyJhb** [comment]
How about just using plain old IRC? - Getting real tired of this moving to Slack/Discord, for features that aren't used, and huge ressource waste.

**Comment by arkag** [comment]
I feel like switching to IRC would lose a lot of users and make getting support more difficult in a lot of cases. 

Don't get me wrong, I like IRC, but it's more annoying to set up than Slack/Discord/Keybase.

**Comment by eyJhb** [comment]
Just link to any web based IRC client?

https://webchat.freenode.net/
http://search.mibbit.com/
https://kiwiirc.com/
https://www.irccloud.com/

List goes on. I think it is a shame, that so many projects start moving over to Slack/Discord, seeing as it is just as much a pain like IRC, just slower and more useless 99% of the time.

**Comment by ColdHeat** [comment]
The features of Slack or Discord might not be used by regular users but I definitely make use of Slack's features and other integrations with Slack. IRC just isn't as nice as Slack or Discord. If there's a strong desire for it I'd certainly consider it but I personally think it's a step backwards.

**Comment by eyJhb** [comment]
@ColdHeat I haven't seen a single feature from Slack/Discord actually getting used on the CTFd Slack channel currently. And most features seems are quite useless or easily made in IRC too, which little to no hassle at all.

Personally I see a lot of people who aren't able to either contribute to the project because of the nature of slack/discord (license, open protocols, etc. etc. etc). 
Also generally speaking, I think you would get more people idling in the channels (which might be able to help), than on slack/discord, e.g. I would do so more myself! But currently I myself have to open my browser, and have that running in a lonely tab someplace hugging resources for a couple of TEXT messages, and forgetting about it.

It is really sad in generally seeing, opensource projects moving over to proprietary software.

**Comment by ColdHeat** [comment]
You don't see the features being used because you're not an administrator. 

CTFd is Apache 2.0. No one has complained about any open protocols before. In my experience IRC is fraught with spam, nonsense, and usually people just idling. 

Projects moving to proprietary protocols doesn't affect the project itself. Kubernetes uses Slack, Vue uses Discord.

**Comment by eyJhb** [comment]
The administrative duties shouldn't concern the active contributors, so the features that the people actually using Slack gets are _none_.

Not referring to CTFDs license, but rather that Slack/Discord does not opensource their software, which is a big nono for many people. IRC has SOME spam etc. but that is rather minimal from my experience on Freenode in the past years. And people idle on Slack too...

Docker uses IRC, Gitlab uses IRC, Debian uses IRC, ReactJS uses IRC. Don't see the point of listing stuff that uses one over the other, my main point is that for something as basic as just text (except admin stuff??), Slack/Discord seems overkill, and using IRC wouldn't make it harder for anyone to actually join the discussion since there are MANY web alternatives and easy to setup programs.

**Comment by arkag** [comment]
Considering no one else from the IRC coalition has joined this debate, they're probably idle. ;)

Most people from this community are into switching from Slack to Discord, so that's what's most likely going to happen.

IRC spam is more than just within channels. Being query spammed is a constant issue for me and I shouldn't have to configure my account server side to prevent that.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by arkag** [comment]
@ColdHeat I've just been pointed over to https://spectrum.chat/ for community open source projects and I'm interested in your opinion on it. I haven't done a ton of research into it but it might be a viable alternative considering it's got a web app.

**Comment by 6uhrmittag** [comment]
From a random guy, that just joined the slack channel because I followed this discussion:
- discord offers one account for everything, feels better +1 discord
- it feels like I miss most of the past conversations because slack cuts the history +1 discord

Maybe check out this discussion: https://github.com/neuecc/UniRx/issues/327

Call me lazy, young or stupid, but I decided long time ago that I'll won't even try to join a IRC channel. It just feels so dated compared to the alternatives.

**Comment by Helithumper** [comment]
At least in my experience, IRC is something that - while open - is restrictive to new users and has a (although small) barrier to entry. It is easy to join if you know what you are doing, but it is missing MANY features by default (Chat history, unified applications). If we want to encourage new users to join in on discussions and aid in development, etc... we might want whatever platform to be easy to join and beneficial to new contributions. While IRC _technically_ can complete the same goals as Discord / Slack, it is unable to in an effective and easy-to-setup manner. As such, Discord is gaining traction because of its ease of use, unified authentication, and bountiful default feature set. If the goal of _whichever_ chat platform is chosen is to aid in contribution, feature creation, and problem solving, then we would want whichever platform gives us that ability in the most readily available and easiest to implement fashion.

**Comment by arkag** [comment]
After thinking on this further, I'm kind of at a loss. 

On one hand, the ease of use of Discord is great.

On the other, they are a closed platform that provides the *illusion* of control. It's not actually a server we'd have, it's a segmented portion of the community. Now, I'm not saying we should move to IRC from Slack, but there are a number of collaborative chat applications that we could use instead of Discord or Slack.

1. Matrix/Riot would provide a rich feature set and allow IRC integration very easily if we wanted
2. Gitter is a decent option and it supports GitHub/Lab authentication which means we wouldn't need to manage another account for collaboration.
3. Keybase is a great platform, and I'm partial to it because I already use it.
4. Spectrum might be an option, though I've not actually used it.

What are our thoughts on this?

**Comment by bkimminich** [comment]
In my personal opinion Slack > Gitter > Discord > IRC

**Comment by zteeed** [comment]
Hi, you might be interested by this project:
https://github.com/zteeed/CTFd-discord

**Comment by ColdHeat** [comment]
The CTFd Slack is now in the process of being moved over to https://community.majorleaguecyber.org/ for open source support. Discord might be setup for ad-hoc chat but from testing and feedback there were some issues that people raised:

- Discord has some limits on file uploads and snippets that I personally have found limiting
- Discord has a more gaming connotation
- There were some losses of data control that weren't great. 
- Not open source

Discourse is a little better in the sense that it's open source, self-hosted, and controlled. It's better searched by the public and also can be used for other discussion. Discourse also supports OAuth authentication via MLC which makes sense given the longer term efforts of growing CTFd beyond just competition software. 

The online Slack joiner has been changed to redirect to MLC Community and soon announcements will be made announcing the move and users will be removed from the CTFd Slack after being told where to go.
